dist: trusty
language: rust
rust:
- stable
env:
  global:
  - CRATE_NAME=hclrs
matrix:
  include:
  - env: TARGET=i686-unknown-linux-gnu
    addons:
      apt:
        packages:
        - gcc-multilib
  - env: TARGET=i686-unknown-linux-musl
    addons:
      apt:
        packages:
        - gcc-multilib
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=x86_64-apple-darwin
    os: osx
before_install: set -e
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
deploy:
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  provider: releases
  skip_cleanup: true
  api_key:
    secure: rb8QaActaFjVM8Y4GbN0y3sgAhlcyjvEBrlWBQQ357WV/rnO5L6CUsFAcFL1gD4lY5HeetP6rHLV6EEE9gB1lJJOKBuboRgNuRUi5+T97bymArGobkTHLFVLqgGsDG8AC0UCVpq2gP8ws5B7pIdrcRViWZZ97QJ+RQtE1BG5tZknhZihMXH/AHEU70IV5GZBeoduQnKCAlT+vqaKXia9K9LRZ69zqc0RBtYxBZuWSSIoSrx48EO/BJbPFV2JXetjj84Q85LwyRRn92QgYLtIpSER7VvJFIZw16wTl0cOuYh9vjaXkE/tvYNS3O+7TQZb/JY7lxPR77Qg3UulLSpQr6jU6lo0bzSX3eGws6Fty7SIFROIx1f4jiKI00TI53Yq+756A3Dd7zBLludOTBIctPi58xBGLxS6VkkG5qzoFhDrtUrTyBZ5y7KA8zjfOv0DV2lIpf0EEykqANxFWJAr/8JxNna7acjJZBYMwBLUzBNii/Jr6fJgd1/s2MiS9xNtOBG2Mk8D48ykgDAhR7VZMdPAkFVRHC5ddLG08nm0PdhGLdB+klQY4jDAqbszOkagMoDNbvemlPLjYsBpJ7OOgOpFHKUay/2aM1ei2UUFoHgnFyaydknYD3mpsSCs1lQghJ7+dh2jypnZtCJyNrW/lH8KeqqJfPVSRweQw+83/EY=
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
